### ISSUE TITLE
Warn users of need to edit rdisk #

### ISSUE THREAD

**Issue by skikirkwood** [gilesw/volumio-customizations#1]
Hi Giles, you may want to warn users of the script 00-mac-prep-sd-card.sh that the number of the disk varies by system, depending upon how many drives you have connected to your system.  For my iMac it is usually rdisk4, but sometimes rdisk5.  Otherwise the script will destroy the contents of someone's external drive!

**Comment by gilesw** [comment]
I've added some checks for macbook model now
